/* A recursive-descent parser generated by greg 0.4.4 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct _GREG;
#define G ctx
#define YYRULECOUNT 37

# include "tree.h"
# include "version.h"

# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# include <string.h>
# include <libgen.h>
# include <assert.h>

  typedef struct Header Header;

  struct Header {
    char   *text;
    Header *next;
  };

  FILE *input= 0;

  int   verboseFlag= 0;

  static int	 lineNumber= 0;
  static char	*fileName= 0;
  static char	*trailer= 0;
  static Header	*headers= 0;

  void makeHeader(char *text);
  void makeTrailer(char *text);

  void yyerror(struct _GREG *, char *message);

# define YY_INPUT(buf, result, max, D)		\
  {						\
    int c= getc(input);				\
    if ('\n' == c || '\r' == c) ++lineNumber;	\
    result= (EOF == c) ? 0 : (*(buf)= c, 1);	\
  }

# define YY_LOCAL(T)	static T
# define YY_RULE(T)	static T

#ifndef YY_ALLOC
#define YY_ALLOC(N, D) malloc(N)
#endif
#ifndef YY_CALLOC
#define YY_CALLOC(N, S, D) calloc(N, S)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(B, N, D) realloc(B, N)
#endif
#ifndef YY_FREE
#define YY_FREE free
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)     static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)    static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)      static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)     T
#endif
#ifndef YY_NAME
#define YY_NAME(N) yy##N
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size, D)              \
  {                                                     \
    int yyc= getchar();                                 \
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);        \
    yyprintf((stderr, "<%c>", yyc));                  \
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN        ( ctx->begin= ctx->pos, 1)
#endif
#ifndef YY_END
#define YY_END          ( ctx->end= ctx->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args) fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE int
#endif
#ifndef YY_XTYPE
#define YY_XTYPE void *
#endif
#ifndef YY_XVAR
#define YY_XVAR yyxvar
#endif

#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_START_SIZE
#define YY_BUFFER_START_SIZE 1024
#endif

#ifndef YY_PART
#define yydata ctx->data
#define yy ctx->ss

struct _yythunk; // forward declaration
typedef void (*yyaction)(struct _GREG *ctx, char *yytext, int yyleng, struct _yythunk *thunkpos, YY_XTYPE YY_XVAR);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

typedef struct _GREG {
  char *buf;
  int buflen;
  int   offset;
  int   pos;
  int   limit;
  char *text;
  int   textlen;
  int   begin;
  int   end;
  yythunk *thunks;
  int   thunkslen;
  int thunkpos;
  YYSTYPE ss;
  YYSTYPE *val;
  YYSTYPE *vals;
  int valslen;
  YY_XTYPE data;
} GREG;

YY_LOCAL(int) yyrefill(GREG *ctx)
{
  int yyn;
  while (ctx->buflen - ctx->pos < 512)
    {
      ctx->buflen *= 2;
      ctx->buf= (char*)YY_REALLOC(ctx->buf, ctx->buflen, ctx->data);
    }
  YY_INPUT((ctx->buf + ctx->pos), yyn, (ctx->buflen - ctx->pos), ctx->data);
  if (!yyn) return 0;
  ctx->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(GREG *ctx)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  ++ctx->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(GREG *ctx, int c)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  if ((unsigned char)ctx->buf[ctx->pos] == c)
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(GREG *ctx, const char *s)
{
  int yysav= ctx->pos;
  while (*s)
    {
      if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
      if (ctx->buf[ctx->pos] != *s)
        {
          ctx->pos= yysav;
          return 0;
        }
      ++s;
      ++ctx->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(GREG *ctx, unsigned char *bits)
{
  int c;
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  c= (unsigned char)ctx->buf[ctx->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(void) yyDo(GREG *ctx, yyaction action, int begin, int end)
{
  while (ctx->thunkpos >= ctx->thunkslen)
    {
      ctx->thunkslen *= 2;
      ctx->thunks= (yythunk*)YY_REALLOC(ctx->thunks, sizeof(yythunk) * ctx->thunkslen, ctx->data);
    }
  ctx->thunks[ctx->thunkpos].begin=  begin;
  ctx->thunks[ctx->thunkpos].end=    end;
  ctx->thunks[ctx->thunkpos].action= action;
  ++ctx->thunkpos;
}

YY_LOCAL(int) yyText(GREG *ctx, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (ctx->textlen < (yyleng + 1))
        {
          ctx->textlen *= 2;
          ctx->text= (char*)YY_REALLOC(ctx->text, ctx->textlen, ctx->data);
        }
      memcpy(ctx->text, ctx->buf + begin, yyleng);
    }
  ctx->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(GREG *ctx)
{
  int pos;
  for (pos= 0; pos < ctx->thunkpos; ++pos)
    {
      yythunk *thunk= &ctx->thunks[pos];
      int yyleng= thunk->end ? yyText(ctx, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, ctx->text));
      thunk->action(ctx, ctx->text, yyleng, thunk, ctx->data);
    }
  ctx->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(GREG *ctx)
{
  if ((ctx->limit -= ctx->pos))
    {
      memmove(ctx->buf, ctx->buf + ctx->pos, ctx->limit);
    }
  ctx->offset += ctx->pos;
  ctx->begin -= ctx->pos;
  ctx->end -= ctx->pos;
  ctx->pos= ctx->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(GREG *ctx, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(ctx);
      yyCommit(ctx);
    }
  return 1;
}

YY_LOCAL(void) yyPush(GREG *ctx, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR) { ctx->val += count; }
YY_LOCAL(void) yyPop(GREG *ctx, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { ctx->val -= count; }
YY_LOCAL(void) yySet(GREG *ctx, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { ctx->val[count]= ctx->ss; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(ctx, yythunkpos0)

YY_RULE(int) yy_end_of_line(GREG *ctx); /* 37 */
YY_RULE(int) yy_comment(GREG *ctx); /* 36 */
YY_RULE(int) yy_space(GREG *ctx); /* 35 */
YY_RULE(int) yy_braces(GREG *ctx); /* 34 */
YY_RULE(int) yy_range(GREG *ctx); /* 33 */
YY_RULE(int) yy_char(GREG *ctx); /* 32 */
YY_RULE(int) yy_errblock(GREG *ctx); /* 31 */
YY_RULE(int) yy_END(GREG *ctx); /* 30 */
YY_RULE(int) yy_BEGIN(GREG *ctx); /* 29 */
YY_RULE(int) yy_DOT(GREG *ctx); /* 28 */
YY_RULE(int) yy_class(GREG *ctx); /* 27 */
YY_RULE(int) yy_literal(GREG *ctx); /* 26 */
YY_RULE(int) yy_CLOSE(GREG *ctx); /* 25 */
YY_RULE(int) yy_OPEN(GREG *ctx); /* 24 */
YY_RULE(int) yy_COLON(GREG *ctx); /* 23 */
YY_RULE(int) yy_PLUS(GREG *ctx); /* 22 */
YY_RULE(int) yy_STAR(GREG *ctx); /* 21 */
YY_RULE(int) yy_QUESTION(GREG *ctx); /* 20 */
YY_RULE(int) yy_primary(GREG *ctx); /* 19 */
YY_RULE(int) yy_NOT(GREG *ctx); /* 18 */
YY_RULE(int) yy_suffix(GREG *ctx); /* 17 */
YY_RULE(int) yy_action(GREG *ctx); /* 16 */
YY_RULE(int) yy_AND(GREG *ctx); /* 15 */
YY_RULE(int) yy_prefix(GREG *ctx); /* 14 */
YY_RULE(int) yy_BAR(GREG *ctx); /* 13 */
YY_RULE(int) yy_sequence(GREG *ctx); /* 12 */
YY_RULE(int) yy_SEMICOLON(GREG *ctx); /* 11 */
YY_RULE(int) yy_expression(GREG *ctx); /* 10 */
YY_RULE(int) yy_EQUAL(GREG *ctx); /* 9 */
YY_RULE(int) yy_identifier(GREG *ctx); /* 8 */
YY_RULE(int) yy_RPERCENT(GREG *ctx); /* 7 */
YY_RULE(int) yy_end_of_file(GREG *ctx); /* 6 */
YY_RULE(int) yy_trailer(GREG *ctx); /* 5 */
YY_RULE(int) yy_definition(GREG *ctx); /* 4 */
YY_RULE(int) yy_declaration(GREG *ctx); /* 3 */
YY_RULE(int) yy__(GREG *ctx); /* 2 */
YY_RULE(int) yy_grammar(GREG *ctx); /* 1 */

YY_ACTION(void) yy_10_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_10_primary\n"));
   Node *node = pop(); ((struct Any *) node)->errblock = strdup(yytext); push(node); ;
}
YY_ACTION(void) yy_9_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_9_primary\n"));
   push(makePredicate("YY_END")); ;
}
YY_ACTION(void) yy_8_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_8_primary\n"));
   push(makePredicate("YY_BEGIN")); ;
}
YY_ACTION(void) yy_7_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_7_primary\n"));
   push(makeAction(yytext)); ;
}
YY_ACTION(void) yy_6_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_6_primary\n"));
   push(makeDot()); ;
}
YY_ACTION(void) yy_5_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_5_primary\n"));
   push(makeClass(yytext)); ;
}
YY_ACTION(void) yy_4_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_4_primary\n"));
   push(makeString(yytext)); ;
}
YY_ACTION(void) yy_3_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_3_primary\n"));
   push(makeName(findRule(yytext))); ;
}
YY_ACTION(void) yy_2_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_primary\n"));
   Node *name= makeName(findRule(yytext));  name->name.variable= pop();  push(name); ;
}
YY_ACTION(void) yy_1_primary(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_primary\n"));
   push(makeVariable(yytext)); ;
}
YY_ACTION(void) yy_3_suffix(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_3_suffix\n"));
   push(makePlus (pop())); ;
}
YY_ACTION(void) yy_2_suffix(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_suffix\n"));
   push(makeStar (pop())); ;
}
YY_ACTION(void) yy_1_suffix(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_suffix\n"));
   push(makeQuery(pop())); ;
}
YY_ACTION(void) yy_3_prefix(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_3_prefix\n"));
   push(makePeekNot(pop())); ;
}
YY_ACTION(void) yy_2_prefix(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_prefix\n"));
   push(makePeekFor(pop())); ;
}
YY_ACTION(void) yy_1_prefix(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_prefix\n"));
   push(makePredicate(yytext)); ;
}
YY_ACTION(void) yy_1_sequence(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_sequence\n"));
   Node *f= pop();  push(Sequence_append(pop(), f)); ;
}
YY_ACTION(void) yy_1_expression(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_expression\n"));
   Node *f= pop();  push(Alternate_append(pop(), f)); ;
}
YY_ACTION(void) yy_2_definition(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_definition\n"));
   Node *e= pop();  Rule_setExpression(pop(), e); ;
}
YY_ACTION(void) yy_1_definition(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_definition\n"));
   if (push(beginRule(findRule(yytext)))->rule.expression)
							    fprintf(stderr, "rule '%s' redefined\n", yytext); ;
}
YY_ACTION(void) yy_1_trailer(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_trailer\n"));
   makeTrailer(yytext); ;
}
YY_ACTION(void) yy_1_declaration(GREG *ctx, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_declaration\n"));
   makeHeader(yytext); ;
}

YY_RULE(int) yy_end_of_line(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "end_of_line"));
  {  int yypos2= ctx->pos, yythunkpos2= ctx->thunkpos;  if (!yymatchString(ctx, "\r\n")) goto l3;  goto l2;
  l3:;	  ctx->pos= yypos2; ctx->thunkpos= yythunkpos2;  if (!yymatchChar(ctx, '\n')) goto l4;  goto l2;
  l4:;	  ctx->pos= yypos2; ctx->thunkpos= yythunkpos2;  if (!yymatchChar(ctx, '\r')) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "end_of_line", ctx->buf+ctx->pos));
  return 1;
  l1:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "end_of_line", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_comment(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "comment"));  if (!yymatchChar(ctx, '#')) goto l5;
  l6:;	
  {  int yypos7= ctx->pos, yythunkpos7= ctx->thunkpos;
  {  int yypos8= ctx->pos, yythunkpos8= ctx->thunkpos;  if (!yy_end_of_line(ctx)) { goto l8; }  goto l7;
  l8:;	  ctx->pos= yypos8; ctx->thunkpos= yythunkpos8;
  }  if (!yymatchDot(ctx)) goto l7;  goto l6;
  l7:;	  ctx->pos= yypos7; ctx->thunkpos= yythunkpos7;
  }  if (!yy_end_of_line(ctx)) { goto l5; }
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", ctx->buf+ctx->pos));
  return 1;
  l5:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_space(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "space"));
  {  int yypos10= ctx->pos, yythunkpos10= ctx->thunkpos;  if (!yymatchChar(ctx, ' ')) goto l11;  goto l10;
  l11:;	  ctx->pos= yypos10; ctx->thunkpos= yythunkpos10;  if (!yymatchChar(ctx, '\t')) goto l12;  goto l10;
  l12:;	  ctx->pos= yypos10; ctx->thunkpos= yythunkpos10;  if (!yy_end_of_line(ctx)) { goto l9; }
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "space", ctx->buf+ctx->pos));
  return 1;
  l9:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_braces(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "braces"));
  {  int yypos14= ctx->pos, yythunkpos14= ctx->thunkpos;  if (!yymatchChar(ctx, '{')) goto l15;
  l16:;	
  {  int yypos17= ctx->pos, yythunkpos17= ctx->thunkpos;  if (!yy_braces(ctx)) { goto l17; }  goto l16;
  l17:;	  ctx->pos= yypos17; ctx->thunkpos= yythunkpos17;
  }  if (!yymatchChar(ctx, '}')) goto l15;  goto l14;
  l15:;	  ctx->pos= yypos14; ctx->thunkpos= yythunkpos14;
  {  int yypos18= ctx->pos, yythunkpos18= ctx->thunkpos;  if (!yymatchChar(ctx, '}')) goto l18;  goto l13;
  l18:;	  ctx->pos= yypos18; ctx->thunkpos= yythunkpos18;
  }  if (!yymatchDot(ctx)) goto l13;
  }
  l14:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "braces", ctx->buf+ctx->pos));
  return 1;
  l13:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "braces", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_range(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "range"));
  {  int yypos20= ctx->pos, yythunkpos20= ctx->thunkpos;  if (!yy_char(ctx)) { goto l21; }  if (!yymatchChar(ctx, '-')) goto l21;  if (!yy_char(ctx)) { goto l21; }  goto l20;
  l21:;	  ctx->pos= yypos20; ctx->thunkpos= yythunkpos20;  if (!yy_char(ctx)) { goto l19; }
  }
  l20:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "range", ctx->buf+ctx->pos));
  return 1;
  l19:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "range", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_char(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "char"));
  {  int yypos23= ctx->pos, yythunkpos23= ctx->thunkpos;  if (!yymatchChar(ctx, '\\')) goto l24;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\204\040\000\000\000\000\000\070\146\100\124\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l24;  goto l23;
  l24:;	  ctx->pos= yypos23; ctx->thunkpos= yythunkpos23;  if (!yymatchChar(ctx, '\\')) goto l25;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\017\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l25;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l25;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l25;  goto l23;
  l25:;	  ctx->pos= yypos23; ctx->thunkpos= yythunkpos23;  if (!yymatchChar(ctx, '\\')) goto l26;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;
  {  int yypos27= ctx->pos, yythunkpos27= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l27;  goto l28;
  l27:;	  ctx->pos= yypos27; ctx->thunkpos= yythunkpos27;
  }
  l28:;	  goto l23;
  l26:;	  ctx->pos= yypos23; ctx->thunkpos= yythunkpos23;
  {  int yypos29= ctx->pos, yythunkpos29= ctx->thunkpos;  if (!yymatchChar(ctx, '\\')) goto l29;  goto l22;
  l29:;	  ctx->pos= yypos29; ctx->thunkpos= yythunkpos29;
  }  if (!yymatchDot(ctx)) goto l22;
  }
  l23:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "char", ctx->buf+ctx->pos));
  return 1;
  l22:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "char", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_errblock(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "errblock"));  if (!yymatchString(ctx, "~{")) goto l30;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l30;
  l31:;	
  {  int yypos32= ctx->pos, yythunkpos32= ctx->thunkpos;  if (!yy_braces(ctx)) { goto l32; }  goto l31;
  l32:;	  ctx->pos= yypos32; ctx->thunkpos= yythunkpos32;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l30;  if (!yymatchChar(ctx, '}')) goto l30;  if (!yy__(ctx)) { goto l30; }
  yyprintf((stderr, "  ok   %s @ %s\n", "errblock", ctx->buf+ctx->pos));
  return 1;
  l30:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "errblock", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_END(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "END"));  if (!yymatchChar(ctx, '>')) goto l33;  if (!yy__(ctx)) { goto l33; }
  yyprintf((stderr, "  ok   %s @ %s\n", "END", ctx->buf+ctx->pos));
  return 1;
  l33:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "END", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_BEGIN(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "BEGIN"));  if (!yymatchChar(ctx, '<')) goto l34;  if (!yy__(ctx)) { goto l34; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BEGIN", ctx->buf+ctx->pos));
  return 1;
  l34:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BEGIN", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_DOT(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "DOT"));  if (!yymatchChar(ctx, '.')) goto l35;  if (!yy__(ctx)) { goto l35; }
  yyprintf((stderr, "  ok   %s @ %s\n", "DOT", ctx->buf+ctx->pos));
  return 1;
  l35:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DOT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_class(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "class"));  if (!yymatchChar(ctx, '[')) goto l36;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l36;
  l37:;	
  {  int yypos38= ctx->pos, yythunkpos38= ctx->thunkpos;
  {  int yypos39= ctx->pos, yythunkpos39= ctx->thunkpos;  if (!yymatchChar(ctx, ']')) goto l39;  goto l38;
  l39:;	  ctx->pos= yypos39; ctx->thunkpos= yythunkpos39;
  }  if (!yy_range(ctx)) { goto l38; }  goto l37;
  l38:;	  ctx->pos= yypos38; ctx->thunkpos= yythunkpos38;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l36;  if (!yymatchChar(ctx, ']')) goto l36;  if (!yy__(ctx)) { goto l36; }
  yyprintf((stderr, "  ok   %s @ %s\n", "class", ctx->buf+ctx->pos));
  return 1;
  l36:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "class", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_literal(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "literal"));
  {  int yypos41= ctx->pos, yythunkpos41= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l42;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l42;
  l43:;	
  {  int yypos44= ctx->pos, yythunkpos44= ctx->thunkpos;
  {  int yypos45= ctx->pos, yythunkpos45= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l45;  goto l44;
  l45:;	  ctx->pos= yypos45; ctx->thunkpos= yythunkpos45;
  }  if (!yy_char(ctx)) { goto l44; }  goto l43;
  l44:;	  ctx->pos= yypos44; ctx->thunkpos= yythunkpos44;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l42;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l42;  if (!yy__(ctx)) { goto l42; }  goto l41;
  l42:;	  ctx->pos= yypos41; ctx->thunkpos= yythunkpos41;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l40;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l40;
  l46:;	
  {  int yypos47= ctx->pos, yythunkpos47= ctx->thunkpos;
  {  int yypos48= ctx->pos, yythunkpos48= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l48;  goto l47;
  l48:;	  ctx->pos= yypos48; ctx->thunkpos= yythunkpos48;
  }  if (!yy_char(ctx)) { goto l47; }  goto l46;
  l47:;	  ctx->pos= yypos47; ctx->thunkpos= yythunkpos47;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l40;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l40;  if (!yy__(ctx)) { goto l40; }
  }
  l41:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "literal", ctx->buf+ctx->pos));
  return 1;
  l40:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "literal", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_CLOSE(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE"));  if (!yymatchChar(ctx, ')')) goto l49;  if (!yy__(ctx)) { goto l49; }
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE", ctx->buf+ctx->pos));
  return 1;
  l49:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OPEN(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OPEN"));  if (!yymatchChar(ctx, '(')) goto l50;  if (!yy__(ctx)) { goto l50; }
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN", ctx->buf+ctx->pos));
  return 1;
  l50:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_COLON(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "COLON"));  if (!yymatchChar(ctx, ':')) goto l51;  if (!yy__(ctx)) { goto l51; }
  yyprintf((stderr, "  ok   %s @ %s\n", "COLON", ctx->buf+ctx->pos));
  return 1;
  l51:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COLON", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_PLUS(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar(ctx, '+')) goto l52;  if (!yy__(ctx)) { goto l52; }
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", ctx->buf+ctx->pos));
  return 1;
  l52:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_STAR(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "STAR"));  if (!yymatchChar(ctx, '*')) goto l53;  if (!yy__(ctx)) { goto l53; }
  yyprintf((stderr, "  ok   %s @ %s\n", "STAR", ctx->buf+ctx->pos));
  return 1;
  l53:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STAR", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_QUESTION(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "QUESTION"));  if (!yymatchChar(ctx, '?')) goto l54;  if (!yy__(ctx)) { goto l54; }
  yyprintf((stderr, "  ok   %s @ %s\n", "QUESTION", ctx->buf+ctx->pos));
  return 1;
  l54:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QUESTION", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_primary(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "primary"));
  {  int yypos56= ctx->pos, yythunkpos56= ctx->thunkpos;  if (!yy_identifier(ctx)) { goto l57; }  yyDo(ctx, yy_1_primary, ctx->begin, ctx->end);  if (!yy_COLON(ctx)) { goto l57; }  if (!yy_identifier(ctx)) { goto l57; }
  {  int yypos58= ctx->pos, yythunkpos58= ctx->thunkpos;  if (!yy_EQUAL(ctx)) { goto l58; }  goto l57;
  l58:;	  ctx->pos= yypos58; ctx->thunkpos= yythunkpos58;
  }  yyDo(ctx, yy_2_primary, ctx->begin, ctx->end);  goto l56;
  l57:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_identifier(ctx)) { goto l59; }
  {  int yypos60= ctx->pos, yythunkpos60= ctx->thunkpos;  if (!yy_EQUAL(ctx)) { goto l60; }  goto l59;
  l60:;	  ctx->pos= yypos60; ctx->thunkpos= yythunkpos60;
  }  yyDo(ctx, yy_3_primary, ctx->begin, ctx->end);  goto l56;
  l59:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_OPEN(ctx)) { goto l61; }  if (!yy_expression(ctx)) { goto l61; }  if (!yy_CLOSE(ctx)) { goto l61; }  goto l56;
  l61:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_literal(ctx)) { goto l62; }  yyDo(ctx, yy_4_primary, ctx->begin, ctx->end);  goto l56;
  l62:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_class(ctx)) { goto l63; }  yyDo(ctx, yy_5_primary, ctx->begin, ctx->end);  goto l56;
  l63:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_DOT(ctx)) { goto l64; }  yyDo(ctx, yy_6_primary, ctx->begin, ctx->end);  goto l56;
  l64:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_action(ctx)) { goto l65; }  yyDo(ctx, yy_7_primary, ctx->begin, ctx->end);  goto l56;
  l65:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_BEGIN(ctx)) { goto l66; }  yyDo(ctx, yy_8_primary, ctx->begin, ctx->end);  goto l56;
  l66:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;  if (!yy_END(ctx)) { goto l55; }  yyDo(ctx, yy_9_primary, ctx->begin, ctx->end);
  }
  l56:;	
  {  int yypos67= ctx->pos, yythunkpos67= ctx->thunkpos;  if (!yy_errblock(ctx)) { goto l67; }  yyDo(ctx, yy_10_primary, ctx->begin, ctx->end);  goto l68;
  l67:;	  ctx->pos= yypos67; ctx->thunkpos= yythunkpos67;
  }
  l68:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "primary", ctx->buf+ctx->pos));
  return 1;
  l55:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "primary", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_NOT(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "NOT"));  if (!yymatchChar(ctx, '!')) goto l69;  if (!yy__(ctx)) { goto l69; }
  yyprintf((stderr, "  ok   %s @ %s\n", "NOT", ctx->buf+ctx->pos));
  return 1;
  l69:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NOT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_suffix(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "suffix"));  if (!yy_primary(ctx)) { goto l70; }
  {  int yypos71= ctx->pos, yythunkpos71= ctx->thunkpos;
  {  int yypos73= ctx->pos, yythunkpos73= ctx->thunkpos;  if (!yy_QUESTION(ctx)) { goto l74; }  yyDo(ctx, yy_1_suffix, ctx->begin, ctx->end);  goto l73;
  l74:;	  ctx->pos= yypos73; ctx->thunkpos= yythunkpos73;  if (!yy_STAR(ctx)) { goto l75; }  yyDo(ctx, yy_2_suffix, ctx->begin, ctx->end);  goto l73;
  l75:;	  ctx->pos= yypos73; ctx->thunkpos= yythunkpos73;  if (!yy_PLUS(ctx)) { goto l71; }  yyDo(ctx, yy_3_suffix, ctx->begin, ctx->end);
  }
  l73:;	  goto l72;
  l71:;	  ctx->pos= yypos71; ctx->thunkpos= yythunkpos71;
  }
  l72:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "suffix", ctx->buf+ctx->pos));
  return 1;
  l70:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "suffix", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_action(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "action"));  if (!yymatchChar(ctx, '{')) goto l76;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l76;
  l77:;	
  {  int yypos78= ctx->pos, yythunkpos78= ctx->thunkpos;  if (!yy_braces(ctx)) { goto l78; }  goto l77;
  l78:;	  ctx->pos= yypos78; ctx->thunkpos= yythunkpos78;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l76;  if (!yymatchChar(ctx, '}')) goto l76;  if (!yy__(ctx)) { goto l76; }
  yyprintf((stderr, "  ok   %s @ %s\n", "action", ctx->buf+ctx->pos));
  return 1;
  l76:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "action", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_AND(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "AND"));  if (!yymatchChar(ctx, '&')) goto l79;  if (!yy__(ctx)) { goto l79; }
  yyprintf((stderr, "  ok   %s @ %s\n", "AND", ctx->buf+ctx->pos));
  return 1;
  l79:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AND", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_prefix(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "prefix"));
  {  int yypos81= ctx->pos, yythunkpos81= ctx->thunkpos;  if (!yy_AND(ctx)) { goto l82; }  if (!yy_action(ctx)) { goto l82; }  yyDo(ctx, yy_1_prefix, ctx->begin, ctx->end);  goto l81;
  l82:;	  ctx->pos= yypos81; ctx->thunkpos= yythunkpos81;  if (!yy_AND(ctx)) { goto l83; }  if (!yy_suffix(ctx)) { goto l83; }  yyDo(ctx, yy_2_prefix, ctx->begin, ctx->end);  goto l81;
  l83:;	  ctx->pos= yypos81; ctx->thunkpos= yythunkpos81;  if (!yy_NOT(ctx)) { goto l84; }  if (!yy_suffix(ctx)) { goto l84; }  yyDo(ctx, yy_3_prefix, ctx->begin, ctx->end);  goto l81;
  l84:;	  ctx->pos= yypos81; ctx->thunkpos= yythunkpos81;  if (!yy_suffix(ctx)) { goto l80; }
  }
  l81:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "prefix", ctx->buf+ctx->pos));
  return 1;
  l80:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "prefix", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_BAR(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "BAR"));  if (!yymatchChar(ctx, '|')) goto l85;  if (!yy__(ctx)) { goto l85; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BAR", ctx->buf+ctx->pos));
  return 1;
  l85:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BAR", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_sequence(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "sequence"));  if (!yy_prefix(ctx)) { goto l86; }
  l87:;	
  {  int yypos88= ctx->pos, yythunkpos88= ctx->thunkpos;  if (!yy_prefix(ctx)) { goto l88; }  yyDo(ctx, yy_1_sequence, ctx->begin, ctx->end);  goto l87;
  l88:;	  ctx->pos= yypos88; ctx->thunkpos= yythunkpos88;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "sequence", ctx->buf+ctx->pos));
  return 1;
  l86:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sequence", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_SEMICOLON(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "SEMICOLON"));  if (!yymatchChar(ctx, ';')) goto l89;  if (!yy__(ctx)) { goto l89; }
  yyprintf((stderr, "  ok   %s @ %s\n", "SEMICOLON", ctx->buf+ctx->pos));
  return 1;
  l89:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SEMICOLON", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_expression(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "expression"));  if (!yy_sequence(ctx)) { goto l90; }
  l91:;	
  {  int yypos92= ctx->pos, yythunkpos92= ctx->thunkpos;  if (!yy_BAR(ctx)) { goto l92; }  if (!yy_sequence(ctx)) { goto l92; }  yyDo(ctx, yy_1_expression, ctx->begin, ctx->end);  goto l91;
  l92:;	  ctx->pos= yypos92; ctx->thunkpos= yythunkpos92;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "expression", ctx->buf+ctx->pos));
  return 1;
  l90:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expression", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_EQUAL(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "EQUAL"));  if (!yymatchChar(ctx, '=')) goto l93;  if (!yy__(ctx)) { goto l93; }
  yyprintf((stderr, "  ok   %s @ %s\n", "EQUAL", ctx->buf+ctx->pos));
  return 1;
  l93:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EQUAL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_identifier(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l94;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\040\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l94;
  l95:;	
  {  int yypos96= ctx->pos, yythunkpos96= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l96;  goto l95;
  l96:;	  ctx->pos= yypos96; ctx->thunkpos= yythunkpos96;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l94;  if (!yy__(ctx)) { goto l94; }
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", ctx->buf+ctx->pos));
  return 1;
  l94:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_RPERCENT(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "RPERCENT"));  if (!yymatchString(ctx, "%}")) goto l97;  if (!yy__(ctx)) { goto l97; }
  yyprintf((stderr, "  ok   %s @ %s\n", "RPERCENT", ctx->buf+ctx->pos));
  return 1;
  l97:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RPERCENT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_end_of_file(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "end_of_file"));
  {  int yypos99= ctx->pos, yythunkpos99= ctx->thunkpos;  if (!yymatchDot(ctx)) goto l99;  goto l98;
  l99:;	  ctx->pos= yypos99; ctx->thunkpos= yythunkpos99;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "end_of_file", ctx->buf+ctx->pos));
  return 1;
  l98:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "end_of_file", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_trailer(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "trailer"));  if (!yymatchString(ctx, "%%")) goto l100;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l100;
  l101:;	
  {  int yypos102= ctx->pos, yythunkpos102= ctx->thunkpos;  if (!yymatchDot(ctx)) goto l102;  goto l101;
  l102:;	  ctx->pos= yypos102; ctx->thunkpos= yythunkpos102;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l100;  yyDo(ctx, yy_1_trailer, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "trailer", ctx->buf+ctx->pos));
  return 1;
  l100:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "trailer", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_definition(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "definition"));  if (!yy_identifier(ctx)) { goto l103; }  yyDo(ctx, yy_1_definition, ctx->begin, ctx->end);  if (!yy_EQUAL(ctx)) { goto l103; }  if (!yy_expression(ctx)) { goto l103; }  yyDo(ctx, yy_2_definition, ctx->begin, ctx->end);
  {  int yypos104= ctx->pos, yythunkpos104= ctx->thunkpos;  if (!yy_SEMICOLON(ctx)) { goto l104; }  goto l105;
  l104:;	  ctx->pos= yypos104; ctx->thunkpos= yythunkpos104;
  }
  l105:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "definition", ctx->buf+ctx->pos));
  return 1;
  l103:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "definition", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_declaration(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "declaration"));  if (!yymatchString(ctx, "%{")) goto l106;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l106;
  l107:;	
  {  int yypos108= ctx->pos, yythunkpos108= ctx->thunkpos;
  {  int yypos109= ctx->pos, yythunkpos109= ctx->thunkpos;  if (!yymatchString(ctx, "%}")) goto l109;  goto l108;
  l109:;	  ctx->pos= yypos109; ctx->thunkpos= yythunkpos109;
  }  if (!yymatchDot(ctx)) goto l108;  goto l107;
  l108:;	  ctx->pos= yypos108; ctx->thunkpos= yythunkpos108;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l106;  if (!yy_RPERCENT(ctx)) { goto l106; }  yyDo(ctx, yy_1_declaration, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "declaration", ctx->buf+ctx->pos));
  return 1;
  l106:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "declaration", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy__(GREG *ctx)
{
  yyprintf((stderr, "%s\n", "_"));
  l111:;	
  {  int yypos112= ctx->pos, yythunkpos112= ctx->thunkpos;
  {  int yypos113= ctx->pos, yythunkpos113= ctx->thunkpos;  if (!yy_space(ctx)) { goto l114; }  goto l113;
  l114:;	  ctx->pos= yypos113; ctx->thunkpos= yythunkpos113;  if (!yy_comment(ctx)) { goto l112; }
  }
  l113:;	  goto l111;
  l112:;	  ctx->pos= yypos112; ctx->thunkpos= yythunkpos112;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", ctx->buf+ctx->pos));
  return 1;
}
YY_RULE(int) yy_grammar(GREG *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "grammar"));  if (!yy__(ctx)) { goto l115; }
  {  int yypos118= ctx->pos, yythunkpos118= ctx->thunkpos;  if (!yy_declaration(ctx)) { goto l119; }  goto l118;
  l119:;	  ctx->pos= yypos118; ctx->thunkpos= yythunkpos118;  if (!yy_definition(ctx)) { goto l115; }
  }
  l118:;	
  l116:;	
  {  int yypos117= ctx->pos, yythunkpos117= ctx->thunkpos;
  {  int yypos120= ctx->pos, yythunkpos120= ctx->thunkpos;  if (!yy_declaration(ctx)) { goto l121; }  goto l120;
  l121:;	  ctx->pos= yypos120; ctx->thunkpos= yythunkpos120;  if (!yy_definition(ctx)) { goto l117; }
  }
  l120:;	  goto l116;
  l117:;	  ctx->pos= yypos117; ctx->thunkpos= yythunkpos117;
  }
  {  int yypos122= ctx->pos, yythunkpos122= ctx->thunkpos;  if (!yy_trailer(ctx)) { goto l122; }  goto l123;
  l122:;	  ctx->pos= yypos122; ctx->thunkpos= yythunkpos122;
  }
  l123:;	  if (!yy_end_of_file(ctx)) { goto l115; }
  yyprintf((stderr, "  ok   %s @ %s\n", "grammar", ctx->buf+ctx->pos));
  return 1;
  l115:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "grammar", ctx->buf+ctx->pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(GREG *ctx);

YY_PARSE(int) YY_NAME(parse_from)(GREG *ctx, yyrule yystart)
{
  int yyok;
  if (!ctx->buflen)
    {
      ctx->buflen= YY_BUFFER_START_SIZE;
      ctx->buf= (char*)YY_ALLOC(ctx->buflen, ctx->data);
      ctx->textlen= YY_BUFFER_START_SIZE;
      ctx->text= (char*)YY_ALLOC(ctx->textlen, ctx->data);
      ctx->thunkslen= YY_STACK_SIZE;
      ctx->thunks= (yythunk*)YY_ALLOC(sizeof(yythunk) * ctx->thunkslen, ctx->data);
      ctx->valslen= YY_STACK_SIZE;
      ctx->vals= (YYSTYPE*)YY_ALLOC(sizeof(YYSTYPE) * ctx->valslen, ctx->data);
      ctx->begin= ctx->end= ctx->pos= ctx->limit= ctx->thunkpos= 0;
    }
  ctx->pos = 0;
  ctx->begin= ctx->end= ctx->pos;
  ctx->thunkpos= 0;
  ctx->val= ctx->vals;
  yyok= yystart(ctx);
  if (yyok) yyDone(ctx);
  yyCommit(ctx);
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
}

YY_PARSE(int) YY_NAME(parse)(GREG *ctx)
{
  return YY_NAME(parse_from)(ctx, yy_grammar);
}

YY_PARSE(void) YY_NAME(init)(GREG *ctx)
{
    memset(ctx, 0, sizeof(GREG));
}
YY_PARSE(void) YY_NAME(deinit)(GREG *ctx)
{
    if (ctx->buf) YY_FREE(ctx->buf);
    if (ctx->text) YY_FREE(ctx->text);
    if (ctx->thunks) YY_FREE(ctx->thunks);
    if (ctx->vals) YY_FREE(ctx->vals);
}
YY_PARSE(GREG *) YY_NAME(parse_new)(YY_XTYPE data)
{
  GREG *ctx = (GREG *)YY_CALLOC(1, sizeof(GREG), ctx->data);
  ctx->data = data;
  return ctx;
}

YY_PARSE(void) YY_NAME(parse_free)(GREG *ctx)
{
  YY_NAME(deinit)(ctx);
  YY_FREE(ctx);
}

#endif


void yyerror(struct _GREG *G, char *message)
{
  fprintf(stderr, "%s:%d: %s", fileName, lineNumber, message);
  if (G->text[0]) fprintf(stderr, " near token '%s'", G->text);
  if (G->pos < G->limit || !feof(input))
    {
      G->buf[G->limit]= '\0';
      fprintf(stderr, " before text \"");
      while (G->pos < G->limit)
	{
	  if ('\n' == G->buf[G->pos] || '\r' == G->buf[G->pos]) break;
	  fputc(G->buf[G->pos++], stderr);
	}
      if (G->pos == G->limit)
	{
	  int c;
	  while (EOF != (c= fgetc(input)) && '\n' != c && '\r' != c)
	    fputc(c, stderr);
	}
      fputc('\"', stderr);
    }
  fprintf(stderr, "\n");
  exit(1);
}

void makeHeader(char *text)
{
  Header *header= (Header *)malloc(sizeof(Header));
  header->text= strdup(text);
  header->next= headers;
  headers= header;
}

void makeTrailer(char *text)
{
  trailer= strdup(text);
}

static void version(char *name)
{
  printf("%s version %d.%d.%d\n", name, GREG_MAJOR, GREG_MINOR, GREG_LEVEL);
}

static void usage(char *name)
{
  version(name);
  fprintf(stderr, "usage: %s [<option>...] [<file>...]\n", name);
  fprintf(stderr, "where <option> can be\n");
  fprintf(stderr, "  -h          print this help information\n");
  fprintf(stderr, "  -o <ofile>  write output to <ofile>\n");
  fprintf(stderr, "  -v          be verbose\n");
  fprintf(stderr, "  -V          print version number and exit\n");
  fprintf(stderr, "if no <file> is given, input is read from stdin\n");
  fprintf(stderr, "if no <ofile> is given, output is written to stdout\n");
  exit(1);
}

int main(int argc, char **argv)
{
  GREG *G;
  Node *n;
  int   c;

  output= stdout;
  input= stdin;
  lineNumber= 1;
  fileName= "<stdin>";

  while (-1 != (c= getopt(argc, argv, "Vho:v")))
    {
      switch (c)
	{
	case 'V':
	  version(basename(argv[0]));
	  exit(0);

	case 'h':
	  usage(basename(argv[0]));
	  break;

	case 'o':
	  if (!(output= fopen(optarg, "w")))
	    {
	      perror(optarg);
	      exit(1);
	    }
	  break;

	case 'v':
	  verboseFlag= 1;
	  break;

	default:
	  fprintf(stderr, "for usage try: %s -h\n", argv[0]);
	  exit(1);
	}
    }
  argc -= optind;
  argv += optind;

  G = yyparse_new(NULL);
  if (argc)
    {
      for (;  argc;  --argc, ++argv)
	{
	  if (!strcmp(*argv, "-"))
	    {
	      input= stdin;
	      fileName= "<stdin>";
	    }
	  else
	    {
	      if (!(input= fopen(*argv, "r")))
		{
		  perror(*argv);
		  exit(1);
		}
	      fileName= *argv;
	    }
	  lineNumber= 1;
	  if (!yyparse(G))
	    yyerror(G, "syntax error");
	  if (input != stdin)
	    fclose(input);
	}
    }
  else
    if (!yyparse(G))
      yyerror(G, "syntax error");
  yyparse_free(G);

  if (verboseFlag)
    for (n= rules;  n;  n= n->any.next)
      Rule_print(n);

  Rule_compile_c_header();

  for (; headers;  headers= headers->next)
    fprintf(output, "%s\n", headers->text);

  if (rules)
    Rule_compile_c(rules);

  if (trailer)
    fprintf(output, "%s\n", trailer);

  return 0;
}

